### ISSUE TITLE
movlog-app/services/find_movies_from_omdb.rb

### ISSUE THREAD

**Issue by NicholasDanks** [soafloggers/movlog-app#4]
step: return_api_results seems to have a lot of nested logic. Can this be refactored to another step? It also has numerous error handling. Maybe this can be simplified

**Comment by aditya-utama-wijaya** [comment]
I recalled that Prof. Soumya mentioned it is still okay and reasonable to have nested logic inside the step, because sometimes when we have to change something, it's more reasonable and easier to change a nested logic (one place), rather than to change some smaller parts (different places).
I hope this answer makes sense?
